id: P004282
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN6442
  title: ཚོར་བའི་ཟིན་ཐོ།
  author: ''
  volumes:
    0866fec57eb04f1bbbe64df8e5e5613c:
      image_group_id: I3CN6444
      title: ''
      volume_number: 1
      total_pages: 284
      base_file: v001.txt
