id: P004282
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6442
  title: ཚོར་བའི་ཟིན་ཐོ།
  author: ''
  volumes:
    0866fec57eb04f1bbbe64df8e5e5613c:
      image_group_id: I3CN6444
      title: ''
      volume_number: 1
      total_pages: 284
